### ISSUE TITLE
Tracking Issue - `core-api:2.0`

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/inx-chronicle#1298]
## Description

The core API must be updated to match https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/tip48/tips/TIP-0048/openapi3-core.yaml

### Routes

- [ ] `/account/:account_id/congestion`
- [ ] `/rewards/:output_id`
- [ ] `/validators`
- [ ] `/validators/:account_id`
- [ ] `/committee`
- [ ] `/blocks/issuance`
- [x] `/outputs/:output_id/full`

### Unresolved Questions

Do we need all of these routes?
