### ISSUE TITLE
Tracking Issue - `inx-chronicle:2.0`

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/inx-chronicle#1315]
## Description

This issue outlines the remaining work needed to bring inx-chronicle to v2.0.

### Remaining Work

- [ ] Ensure API completely matches spec / expectations from explorer #1298
- [ ] Update internal API spec documents
- [ ] Update docker config
- [ ] Fix or remove commented tests

### Unresolved Questions

- Are there endpoints outside of #1298 that are needed for the explorer?
- Should we attempt to switch databases?

**Comment by DaughterOfMars** [comment]
Blocked by https://github.com/iotaledger/iota-core/issues/749
