### ISSUE TITLE
Tracking Issue - `Analytics`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#15]
There are several statistics that can help us better understand how a network is used. The following analytic endpoints should be supported by Chronicle:

* [x] #328
  * [x] Total number of minted NFTs
  * [x] Total number of native tokens created
  * [x] #424
* [ ] #329
  * [x] #419
  * [x] #423
  * [x] #516

The activity analytics should be implemented for set time intervals of 24h, 7d, 30d, and 90d.

In addition to these required statistics @Alexandcoats has some more brainstorming ideas below, which we could tackle afterwards.

Here is what the endpoints will look like:

#### Activity

* [ ] `/activity ?startIndex & endIndex`
  * [x] `/blocks` (total count)
    * [x] `/transaction`
    * [x] `/tagged-data`
    * [x] `/milestone`
    * [x] `/treasury-transaction`
  * [x] `/outputs` (total count/amount created
    * [x] `/alias`
    * [x] `/basic`
    * [x] `/nft`
    * [x] `/foundry`
    * [x] `/storage-deposit` 
  * [x] `/base-tokens` (use ledger update table)
  * [ ] `/native-tokens` (use ledger update table)
  * [ ] `/nfts` (use ledger update table)

#### Ledger Status

* [x] `/ledger ?ledger_index` (total count unspent)
  * [x] `/storage-deposit` (byte cost at ledger index)
  * [x] `/nfts` (count of the number of unspent nft ouputs)
  * [x] `/native-tokens` (count of the number of unspent foundry outputs)

**Comment by Alexandcoats** [comment]
Some requirements:

## Granularity
- [ ] Daily
- [ ] Weekly?
- [ ] Monthly?

## Messages
- [ ] Total
- [ ] Average per second

## Transactions
- [ ] Total
- [ ] Average per second
- [ ] Included count
- [ ] Conflicting count?
- [ ] Transferred tokens

## Outputs
- [ ] Average per address
- [ ] Max per address

## Addresses
- [ ] Total unique used
- [ ] Unique sending
- [ ] Unique Receiving

**Comment by dharam0034** [comment]
hello, i think It would be nice to have a feature to see the "value" activity on tangle (i.e. the number of blocks that contain transaction payloads within a given time period only, excluding other message type of Milestone, Indexed and No payload).

I think "value" TPS (or per day/week) is one of the important metrics from tokenomics point of view.

**Comment by Alexandcoats** [comment]
This information is already (almost) provided by the proposed API, indirectly, as transactions per second/day/week can be calculated easily using the time period given to the API and the total count. However, this does not work if you do not send a start or end time. We could either:

1. Provide the time range in the endpoint response.
2. Directly calculate those values (perhaps based on query params?)
3. Leave the endpoint as-is, so that it is only possible to calculate these values when providing both start and end time.

**Comment by grtlr** [comment]
In general it might be cool to have a `payload` analytics endpoint that counts the number of different payloads during an interval.

**Comment by grtlr** [comment]
Thanks for the feedback @dharam0034! We will provide block level statistics that can be used to generate such a graph.
