### ISSUE TITLE
Tracking Issue - `Node Core API`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#178]
### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### Steps

For now I think we should implement the following routes, focusing on the `GET` requests only:

#### `blocks`

* [x] `/api/v2/blocks/{blockId}`
  * [x] JSON response
  * [x] Binary response
* [x] `/api/v2/blocks/{blockId}/metadata`
* [x] `/api/v2/blocks/{blockId}/children` (will be removed from the Core Node API, but kept in Chronicle)

#### `UTXO`

* [x] `/api/v2/outputs/{outputId}`
* [x] `/api/v2/outputs/{outputId}/metadata`
* [x] `/api/v2/receipts`
* [x] `/api/v2/receipts/{migratedAt}`
* [x] `/api/v2/treasury`
* [x] `/api/v2/transactions/{transactionId}/included-block`

#### `milestones`

* [x] `/api/v2/milestones/{milestoneId}`
* [x] `/api/v2/milestones/{milestoneId}/utxo-changes`
* [x] `/api/v2/milestones/by-index/{index}`
* [x] `/api/v2/milestones/by-index/{index}/utxo-changes`

### Unresolved Questions

Should we use the response types from `bee-rest-api` once https://github.com/iotaledger/bee/pull/1239 is merged? For now I think we can just copy them over from the PR and adapt them to the `Message -> Block` rename.

**Comment by grtlr** [comment]
This has been implemented apart from some minor issues: #316 and #320.
