### ISSUE TITLE
Tracking Issue - `Metrics`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#297]
Currently, the Prometheus metrics are not part of the set of `default-features` in the `Cargo.toml`. The following steps should be taken to re-enable them again and make them more useful:

* [x] #229
* [x] #167
* [x] #147
  * [x] Total number of gaps in milestones (Gauge)
  * [x] Time to handle a single milestone
    * [x] Remove `cone_stream.rs` (similar to #359)
* [x] #411
* [x] Remove `metrics-debug` functionality
* [x] Remove `metrics` feature
* [x] Provide Grafana dashboard JSON file

**Comment by Alexandcoats** [comment]
We should also provide an example grafana dashboard JSON file.

**Comment by grtlr** [comment]
Closed by #577.
