### ISSUE TITLE
Tracking Issue - `Indexer API`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#330]
In addition to the core node API, we should also support the [Indexer API](https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/indexer-api/tips/TIP-0026/indexer-rest-api.yaml). Most of the required information will be in the `BlockDocument` collection already.

The following endpoints have to be implemented:

* [x] #331
  * [ ] `/api/indexer/v1/outputs/basic`
* [x] #332
  * [ ] `/api/indexer/v1/outputs/alias`
  * [ ] `/api/indexer/v1/outputs/alias/{aliasId}`
* [x] #333
  * [ ] `/api/indexer/v1/outputs/foundry`
  * [ ] `/api/indexer/v1/outputs/foundry/{foundryId}`
* [ ] #334
  * [ ] `/api/indexer/v1/outputs/nft`
  * [ ] `/api/indexer/v1/outputs/nft/{nftId}`

The trickiest part of the indexer is to make the parameters of each of these endpoints composable.

* [x] #335

**Comment by grtlr** [comment]
It might make sense to add an additional `output_type` field to the `LedgerUpdateDocument` collection. This way we could easily filter on the output types for the Indexer API. @Alexandcoats what do you think?

**Comment by Alexandcoats** [comment]
We can't really use that collection for this anyway, since it doesn't contain enough information.

**Comment by Alexandcoats** [comment]
Here are some proposals regarding this API:

### Storage
Due to the necessity of pagination for these endpoints, there is no performant option other than storing one or more separate collections for outputs. We can optionally separate the outputs from their block when we store them so as to eliminate data duplication, but this would require that we query across collections to gather a full block and introduce the possibility of de-synchronization between them (solvable by transactions?). This can be put to further discussion irrespective of the choices made herein.

It should be acceptable to have a single additional collection, `stardust_outputs` for instance, which stores one record per output, alongside a type indicator field (effectively the unwound outputs from the block array) and the output ID.

### Indexes
One index must be "create-able" for each index-able property, of which there are many outlined in the Indexer API, meaning that at minimum the indexes should be automatically created at startup, but could potentially be configured with more granularity. A user may desire some indexes more than others, and the choice of which to enable should probably be configurable rather than all-or-nothing. However, for the initial implementation this may not be necessary.

The indexed fields should not need to be flattened, as indexes in mongo are fairly flexible and can be applied deep within documents, though we may run into unforeseen issues here. Each index can be created independently and will be [combined by mongo](https://www.mongodb.com/docs/manual/core/index-intersection/) to the best of its ability.
