### ISSUE TITLE
Tracking Issue - `Fix Syncer`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#496]
### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

#### Simplify syncing logic

* [x] #497
* [x] #498
* [x] #499

#### Transactions

* [x] `insertMany` for `BlockDocument`
  * [ ] Use `#[serde(rename = "_id")]` on `block_id`
* [ ] `insertMany` for `OutputDocument`
  * [ ] Use `#[serde(rename = "_id")]` on `output_id`
  * [ ] Use it for `ReadUnspentOutputs`
* [ ] `insert` for `MilestoneDocument`
  * [ ] Use `#[serde(rename = "_id")]` on `milestone_index`
  * [x] Remove `is_synced`
  * [x] Remove `ledger_index_status`
* [x] Wrap everything in a MongoDB transaction
* [x] Create MongoDB `ReplSet` in `docker-compose.yml`
* [ ] Remove redundant `metadata.output_id` and `block_id`
* [x] Remove `gaps/` call from API

Additional steps

* [x] #505
